### ISSUE TITLE
formalize convention for organizing translations.yml

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/cb-translate#2]
- [x] how items in translations.yml match with the template file structure
- [ ] add comments in the yml with description to help users
- [x] consider handling of repeating labels used in several locations (repeat configuration or reuse single key?)

**Comment by maehr** [comment]
I tried to match the folder and file structure in `_data/translations.yml` and decided not to reuse labels except on the same page. Regarding comments I have not found a good solution yet.
